# File: action.yml
name: Cat Hello File
description: Composite action to print the content of hello.txt

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Display hello.txt content
      run: cat hello.txt
      shell: bash
